# Generated by Django 4.2.24 on 2025-09-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('trekking', 'Trekking'), ('cultural', 'Cultural Tour'), ('adventure', 'Adventure'), ('wildlife', 'Wildlife Safari'), ('pilgrimage', 'Pilgrimage'), ('mountaineering', 'Mountaineering'), ('photography', 'Photography Tour'), ('luxury', 'Luxury Tour')], max_length=20)),
                ('duration_days', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('min_people', models.IntegerField(default=1)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('included_services', models.TextField()),
                ('excluded_services', models.TextField()),
                ('itinerary', models.JSONField(default=dict)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('extreme', 'Extreme')], max_length=20)),
                ('best_season', models.CharField(max_length=100)),
                ('altitude', models.IntegerField(blank=True, help_text='Maximum altitude in meters', null=True)),
                ('equipment_provided', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='accounts.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.package')),
            ],
            options={
                'ordering': ['-is_main', 'created_at'],
            },
        ),
    ]
