# Generated by Django 4.2.24 on 2025-09-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('languages', models.JSONField(default=list)),
                ('specialties', models.JSONField(default=list)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('places_covered', models.TextField(help_text='Comma-separated list of places')),
                ('certifications', models.TextField(blank=True, help_text='Guide certifications and training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='accounts.agency')),
            ],
        ),
    ]
